#!/bin/bash

yellow='\e[1;33m'
green='\e[1;32m'
red='\e[0;31m'
white='\e[1;37m'

Expand1='./Partition1'
Expand2='./Partition2'
Guided='./Guided'
Autowithgui='./Autogui'
Autonogui='./FullAuto'

cd $HOME/temp/scripts
chmod +x *
echo -e "${green}"
echo "Welcome to Cubox-i4pro Webui installer."

#Demand Root.
echo -e "${red}"
while true;do
    read -p "ARE YOU RUNNING THIS AS ROOT? NOT SUDO BUT "ROOT"(yes or no)" yn
    case $yn in
	 [Yy]* ) echo "Starting Script"; break;;
	 [Nn]* ) echo "THIS MUST RUN AS ROOT!";tput sgr0; exit;;
	 * ) echo "Please answer yes or no."; exit;;
 esac
done
clear
echo -e "${green}"
echo "1.Step One of the Expand Process"
echo "2.Step Two of the Expand Process" 
echo "3.Guided Install"
echo "4.Full Auto with GUI"
echo "5.Full Auto without GUI" 
#Guided install
echo -e "${yellow}"
while true;do
    read -p "Please select your install method: " abc
    case $abc in
         [1] ) "${Expand1}"; tput sgr0; break;;
         [2] ) "${Expand2}"; tput sgr0; break;;
         [3] ) "${Guided}"; tput sgr0; break;;
         [4] ) "${Autowithgui}"; tput sgr0; break;;
         [5] ) "${Autonogui}"; tput sgr0; break;;
         [EeQq]* ) echo "Thank You For Trying this out!!"; tput sgr0; exit;;
         * ) echo -e "${red}"; echo "Please Select one of the options or Exit to quit"; echo -e "${yellow}";;
 esac
done
